apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-deployment
  namespace: abc-namespace
  labels:
    app: abc-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: abc-app
  template:
    metadata:
      labels:
        app: abc-app
    spec:
      containers:
        - name: abc-container
          image: suramanjarikesavan/abc_tech:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
