- name: Deploy ABC app to Kubernetes
  hosts: localhost
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: abc-namespace

    - name: Deploy the app deployment
      kubernetes.core.k8s:
        state: present
        namespace: abc-namespace
        src: deployment.yaml

    - name: Deploy the service
      kubernetes.core.k8s:
        state: present
        namespace: abc-namespace
        src: service.yaml
