- name: Deploy ABC app to Kubernetes
  hosts: localhost
  connection: local
  vars:
    kubeconfig: "/root/.kube/config"
  tasks:
    - name: Create namespace
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        definition:
          apiVersion: v1
          kind: Namespace
          metadata:
            name: abc-namespace

    - name: Deploy the app deployment
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: abc-namespace
        src: "{{ workspace }}/deployment.yaml"

    - name: Deploy the service
      kubernetes.core.k8s:
        kubeconfig: "{{ kubeconfig }}"
        state: present
        namespace: abc-namespace
        src: "{{ workspace }}/service.yaml"
