apiVersion: v1
kind: Service
metadata:
  name: abc-service
  namespace: abc-namespace
spec:
  selector:
    app: abc-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer