apiVersion: apps/v1
kind: Deployment
metadata:
  name: abc-tech-deployment
  labels:
    app: abc-tech
spec:
  replicas: 2
  selector:
    matchLabels:
      app: abc-tech
  template:
    metadata:
      labels:
        app: abc-tech
    spec:
      containers:
        - name: abc-tech-container
          image: suramanjarikesavan/abc_tech:latest
          ports:
            - containerPort: 8080
